prompt PL/SQL Developer import file
prompt Created on 2018年1月3日 by Administrator
set feedback off
set define off
prompt Creating SALARY_MANAGE.EMPLOYEE_...
create table SALARY_MANAGE.EMPLOYEE_
(
  ID               NUMBER,
  BANK_ACCOUNT     VARCHAR2(19),
  SAL_NAME         VARCHAR2(10),
  POST_CATEGORY    VARCHAR2(30),
  SAL_ID           VARCHAR2(11) not null,
  SAL_DEP          VARCHAR2(40),
  SAL_POST         VARCHAR2(30),
  SAL_DATE         DATE,
  SAL_OA           VARCHAR2(22),
  STA_CATEGORY     VARCHAR2(30),
  SAL_REMARK       VARCHAR2(50),
  SAL_SKILLLEVEL   VARCHAR2(10),
  SAL_SKILL_SALARY NUMBER(12,2)
)
;
alter table SALARY_MANAGE.EMPLOYEE_
  add constraint PK_EMPLOYEE primary key (SAL_ID);

prompt Loading SALARY_MANAGE.EMPLOYEE_...
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (129, '1111111111111111111', '张三', '管理', '092451', '综合办公室-行政组', '管理人员', to_date('10-10-2017', 'dd-mm-yyyy'), '12121212', '管理-一般管理', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (130, '2222222222222222222', '李四', null, '092452', '综合办公室-行政组', '管理人员', to_date('10-10-2017', 'dd-mm-yyyy'), '00111111', '管理-一般管理', null, null, null);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (131, '3333333333333333333', '安五', null, '092453', '综合办公室-行政组', '管理人员', to_date('10-10-2017', 'dd-mm-yyyy'), '87766776', '管理-一般管理', null, null, null);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (197, '1', '1', null, '092346', '设备动力技改部-技改组', null, null, '735782', '技术-技术开发', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (198, '2', '2', null, '092376', '设备动力技改部-技改组', null, null, '738209', '技术-技术开发', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (199, '3', '3', null, '092463', '设备动力技改部-技改组', null, null, '00739854', '技术-技术开发', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (200, '4', '4', null, '092114', '设备动力技改部-技改组', null, null, '718423.00', '技术-技术开发', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (201, '5', '5', null, '090571', '设备动力技改部-技改组', null, null, '90571', '技术-技术开发', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (202, '6', '6', null, '090079', '设备动力技改部-技改组', null, null, '90079.00', '技术-技术开发', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (203, '7', '7', null, '090518', '设备动力技改部-技改组', null, null, '90518.00', '技术-技术开发', null, '8', 300);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (204, '8', '8', null, '091217', '技术部-信息化组', null, null, '91217.00', '技术-IT技术', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (205, '9', '9', null, '091766', '技术部-信息化组', null, null, '705360.00', '技术-IT技术', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (206, '10', '10', null, '092460', '技术部-信息化组', null, null, '00739804', '技术-IT技术', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (207, '11', '11', null, '091106', '质量部-质量管理组', null, null, '91106.00', '管理-二级机构负责人', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (208, '12', '12', null, '091337', '质量部-质量管理组', null, null, '91337.00', '管理-二级机构负责人', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (209, '13', '13', null, '090233', '质量部-质量管理组', null, null, '90233.00', '管理-二级机构负责人', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (210, '14', '14', null, '090124', '质量部-质量管理组', null, null, '90124.00', '管理-二级机构负责人', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (211, '15', '15', null, '090111', '质量部-质量管理组', null, null, '90111.00', '管理-二级机构负责人', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (212, '16', '16', null, '090182', '中长缸车间-电镀工段', null, null, '90182.00', '生产人员-计时', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (213, '17', '17', null, '090126', '中长缸车间-电镀工段', null, null, '90126.00', '生产人员-计时', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (214, '18', '18', null, '090272', '中长缸车间-电镀工段', null, null, '90272.00', '生产人员-计时', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (215, '19', '19', null, '092282', '中长缸车间-电镀工段', null, null, '723854.00', '生产人员-计时', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (216, '20', '20', null, '090508', '中长缸车间-电镀工段', null, null, '90508.00', '生产人员-计时', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (217, '21', '21', null, '092488', '中长缸车间-电镀工段', null, null, null, '生产人员-计时', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (218, '22', '22', null, '092087', '中长缸车间-电镀工段', null, null, '717395.00', '生产人员-计时', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (219, '23', '23', null, '090339', '中长缸车间-电镀工段', null, null, '90339.00', '生产人员-计时', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (220, '24', '24', null, '091319', '生产经营部-营销组', null, null, '91319.00', '营销人员-售后', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (221, '25', '25', null, '090018', '生产经营部-营销组', null, null, '90018', '营销人员-售后', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (222, '26', '26', null, '091243', '生产经营部-营销组', null, null, '91243', '营销人员-售后', null, null, 0);
insert into SALARY_MANAGE.EMPLOYEE_ (ID, BANK_ACCOUNT, SAL_NAME, POST_CATEGORY, SAL_ID, SAL_DEP, SAL_POST, SAL_DATE, SAL_OA, STA_CATEGORY, SAL_REMARK, SAL_SKILLLEVEL, SAL_SKILL_SALARY)
values (223, '27', '27', null, '090203', '生产经营部-营销组', null, null, '90203.00', '营销人员-售后', null, null, 0);
commit;
prompt 30 records loaded
set feedback on
set define on
prompt Done.
