prompt PL/SQL Developer import file
prompt Created on 2018年1月3日 by Administrator
set feedback off
set define off
prompt Creating SALARY_MANAGE.INSURANCE_...
create table SALARY_MANAGE.INSURANCE_
(
  ID                NUMBER,
  INS_NAME          VARCHAR2(11),
  INS_ID            VARCHAR2(11) not null,
  INS_SEX           VARCHAR2(6),
  INS_BOTH          DATE,
  INS_IDEN          CHAR(18),
  INS_ADDRESS       VARCHAR2(50),
  INS_CAR_NUMBER    VARCHAR2(20),
  INS_OLD_ID        VARCHAR2(20),
  INS_OLD           VARCHAR2(20),
  INS_TREATMENT_ID  VARCHAR2(20),
  INS_TREATMENTS    VARCHAR2(20),
  INS_ILL_ID        VARCHAR2(20),
  INS_ILL           VARCHAR2(20),
  INSURANCE         VARCHAR2(20),
  INS_UNEMP_ID      VARCHAR2(20),
  INS_UNEMP         VARCHAR2(20),
  INS_UNEMP_ADDRESS VARCHAR2(20),
  INS_ACC_FUND      VARCHAR2(20),
  INS_ACC_ADDRESS   VARCHAR2(20),
  INS_SIGN          VARCHAR2(20),
  INS_REMARK        VARCHAR2(50)
)
;
alter table SALARY_MANAGE.INSURANCE_
  add constraint PK_INSURANCE primary key (INS_ID);

prompt Loading SALARY_MANAGE.INSURANCE_...
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (257, '1', '092346', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (258, '2', '092376', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (259, '3', '092463', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (260, '4', '092114', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (261, '5', '090571', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (262, '6', '090079', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (263, '7', '090518', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (264, '8', '091217', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (265, '9', '091766', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (266, '10', '092460', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (267, '11', '091106', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (268, '12', '091337', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (269, '13', '090233', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (270, '14', '090124', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (271, '15', '090111', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (272, '16', '090182', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (273, '17', '090126', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (274, '18', '090272', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (275, '19', '092282', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (276, '20', '090508', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (277, '21', '092488', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (278, '22', '092087', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (279, '23', '090339', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (280, '24', '091319', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (281, '25', '090018', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (282, '26', '091243', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (283, '27', '090203', '男', null, null, null, null, null, '224', '常德', '0', null, '8', '常德', null, '8.4', '常德', '280', '常德', '常德', null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (132, '张三', '092451', '男', null, null, null, null, null, '224', null, '0', null, '0', null, null, '8.4', null, '280', null, null, null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (133, '李四', '092452', '男', null, null, null, null, null, '224', null, '0', null, '0', null, null, '0', null, '280', null, null, null);
insert into SALARY_MANAGE.INSURANCE_ (ID, INS_NAME, INS_ID, INS_SEX, INS_BOTH, INS_IDEN, INS_ADDRESS, INS_CAR_NUMBER, INS_OLD_ID, INS_OLD, INS_TREATMENT_ID, INS_TREATMENTS, INS_ILL_ID, INS_ILL, INSURANCE, INS_UNEMP_ID, INS_UNEMP, INS_UNEMP_ADDRESS, INS_ACC_FUND, INS_ACC_ADDRESS, INS_SIGN, INS_REMARK)
values (134, '安五', '092453', '女', null, null, null, null, null, '224', null, '56', null, '8', null, null, '8.4', null, '280', null, null, null);
commit;
prompt 30 records loaded
set feedback on
set define on
prompt Done.
